name: CI

on: [push]

jobs:

  bootstrap_all_dry_run:
    name: Bootstrap --all --dry-run
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Test script
      run: |
        zsh ./bootstrap.sh -v --dry-run --all --force --ci

  bootstrap_quick:
    name: Bootstrap --ci quick
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Test script
      run: |
        zsh ./bootstrap.sh -v --hello --zsh --git --symlink --nvim --data --macos


  bootstrap_all:
    name: Bootstrap --ci
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Test script
      run: |
        zsh ./bootstrap.sh -v --ci
