name: CI

on: [push]

jobs:
  build:

    runs-on: macos

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        zsh ./bootstrap.sh --all --force
